# Generated by Django 3.2 on 2021-05-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='exercept',
            new_name='excerpt',
        ),
    ]
